### ISSUE TITLE
New example using MySQL

### ISSUE THREAD

**Issue by jm-duro** [OpenEuphoria/euphoria-mvc#11]
Hi Greg,
Here is a new example using MySQL and forms with POST requests. Code for local CSS file is also included but not used because it does not work today.
Regards
Jean-Marc
[mysql_users.zip](https://github.com/OpenEuphoria/euphoria-mvc/files/5602441/mysql_users.zip)

**Comment by ghaberek** [comment]
Response here: https://openeuphoria.org/forum/134759.wc?last_id=135204#135204
