### ISSUE TITLE
load_config fails

### ISSUE THREAD

**Issue by jm-duro** [OpenEuphoria/euphoria-mvc#12]
```
m_comment@mvc\config.e:23 (map #14) = {
C:\My Program Files\euphoria4.1_32\include\mvc\mapdbg.e:228 in procedure print_map()
type_check failure, map_size is {69,117,58,83,116,100,77,97,112}
... called from C:\My Program Files\euphoria4.1_32\include\mvc\config.e:169 in function load_config()
... called from C:\Data\Euphoria\mysql_users\mysql.e:84
```
Same error appears with or without comment in app.cfg.

Jean-Marc

**Comment by ghaberek** [comment]
It would seem you're still using the Euphoria 4.0 standard library. Please make sure you're using Euphoria 4.1 and that Euphoria is pulling in the correct include files. The internal layout and operation of std/map.e changed significantly between versions 4.0 and 4.1 and I'm writing Euphoria MVC based on last beta2 release: `6300:57179171dbed, 2015-02-02 14:18:53`

I plan to push some changes to mvc/mapdbg.e that removes all the debugging info unless `MAPDBG` is defined. I will do that soon. In the mean time, here is a quick test program you can run to verify your installation:

    -- include_paths.ex

    include std/filesys.e
    include std/search.e
    include euphoria/info.e

    sequence info = euphoria_copyright()
    for i = 1 to length(info) do
        info[i] = match_replace("\n", info[i], "\\n")
        printf(1, "info[%d] = \"%s\"\n", {i,info[i]})
    end for

    sequence path = include_paths(0)
    for i = 1 to length(path) do
        path[i] = canonical_path(path[i])
        printf(1, "path[%d] = \"%s\"\n", {i,path[i]})
    end for

**Comment by ghaberek** [comment]
Commit 75fa671c71385bce336a130815b52a063656aa8e adds an `ifdef` guard called `MAPDBG` to enable mvc/mapdbg.e debugging features. It's now disabled by default. Those features are only really used for internal testing to ensure any maps being created by the routing and template modules are getting cleaned up properly and not causing memory leaks. You still need to fix your standard libraries though.
