### ISSUE TITLE
Make routine names more consistent

### ISSUE THREAD

**Issue by ghaberek** [OpenEuphoria/euphoria-mvc#2]
Before we get too far along, we should determine a better naming convention for all routines in the framework. I'm considering the following API structure based on namespaces for each module and using `module:verb()` or `module:verb_noun()`. I will start to implement this soon if there are no objections.

**mvc/app.e**
- `app:add_hook( integer hook_type, sequence name, integer rid )`
- `app:get_method()`
- `app:get_url( sequence name, object response )`
- `app:set_header( sequence name, object value )`
- `app:redirect( sequence url, integer code )`
- `app:response_code( integer code, sequence message )`
- `app:route( sequence name, sequence path, integer rid )`
- `app:start_server()`
- `app:stop_server()`
- `app:run()`

**mvc/config.e**
- `config:load( sequence filename )`
- `config:save( sequence filename, object config_id )`
- `config:get( sequence category, sequence name, object default, object config_id )`
- `config:set( sequence category, sequence name, object value, object config_id )`

**mvc/cookie.e**
- `cookie:get_all()`
- `cookie:get_names()`
- `cookie:get( sequence name, object default )`
- `cookie:set( sequence name, object value )`

**mvc/database.e**
- `db:add_protocol( sequence name )`
- `db:add_plugin( integer proto, sequence plugin_def )`
- `db:connect( sequence url )`
- `db:disconnect( atom handle )`
- `db:select( atom handle )`
- `db:exec_query( sequence query, object params, atom handle )`
- `db:fetch_row( atom result, atom handle )`
- `db:fetch_map( atom result, atom handle )`
- `db:free_result( atom result )`

**mvc/env.e**
- `env:get( sequence name, integer as_type, object default )`
- `env:get_integer( sequence name, integer default )`
- `env:get_number( sequence name, atom default )`
- `env:get_string( sequence name, sequence default )`

**mvc/model.e**
- `model:define( sequence name, sequence model_def )`
- `model:new( integer model_id, object params )`
- `model:get( object model_obj, sequence name, object default )`
- `model:set( object model_obj, sequence name, object value )`
- `model:fetch_one( integer model_id, sequence query, object params )`
- `model:fetch_all( integer model_id, sequence query, object params )`
- `model:store( object model_obj, sequence query, object params )`
- `model:delete( object model_obj, sequence query, object params )`

**mvc/session.e**
- `session:start( sequence app_name )`
- `session:get( sequence name, object default )`
- `session:set( sequence name, object value )`

**mvc/template.e**
- `template:set_path( sequence path )`
- `template:add_function( sequence name, sequence params, integer rid )`
- `template:render( sequence name, object response )`

_**Note:** default parameters omitted for brevity._

**Comment by HighTechForms** [comment]
Seems reasonable. The only thing I'd consider changing is the pair of `model:fetch_one()` and `model:fetch_all()`, which could become `one: model:fetch( integer model_id, sequence query, object params, count=[1|10|ALL|...])`.

**Comment by HighTechForms** [comment]
You could add `model:query(integer model_id, sequence query, object params` or `model:set_query(...)`? Then you could `model:fetch(1)` or `model:fetch(ALL)` or even `model:fetch({first..last})`.
